#+KEYWORDS:  rnaseq, pipeline
#+LANGUAGE:  en
#+OPTIONS:   H:4
#+OPTIONS:   num:nil
#+OPTIONS:   toc:2
#+OPTIONS:   p:t
#+OPTIONS: author:nil date:nil

* Pipeline usage (will be updated)
** Install last version of pipeline
This and all other steps assume that you are using *scc4* cluster.

Run the following command in the directory that you are going to use for RNAseq analysis:

#+begin_src 
git clone https://github.com/mpyatkov/rnaseq_pipeline.git pipeline 
#+end_src

** Start the pipeline
This step assumes that you have already installed anaconda environment and the cloned version of pipeline.

Go to the directory pipeline/Scripts/00_Setup_Pipeline

You will see 2 files (01_Pipeline_Setup.py, 02_Run_Pipeline.sh). The most important ones are *01_Pipeline_Setup.py* and *02_Run_Pipeline.sh*. First of all, you need to run the following command to get configuration files:

#+begin_src sh
./01_Pipeline_Setup.py
#+end_src

It will give you 4 config files:

1) *Pipeline_Setup.conf* - contains all information about locations of samples, project, and other specific details. Probably to run the pipeline it will be enough to fill out only [USER] section.

2) *Sample_Labels.txt* - this files contains information about all samples. The main columns are:
   - *Group* - each sample should be associated with only one group
   - *Condition_Name* - this condition ID will appear in the names of the output files
   - *Sample_DIR* and *Sample_ID* - for simplicity, just use the same names for this parameters.
   - *Description* - the full description of the sample
   - *Color* - the color to be used in the UCSC browser

3) *Comparisons.txt* - contains information about which groups should be compared. The main rule here: *Condition_2/Condition_1*. Information from this step is required to generate directories for Differential Expression.

4) *venn_comparisons.txt* - Allows to specify which groups of samples will be subject to different venn comparisons (numbers correspond to Comparison_Number column from Comparison.txt):
   
*WARNING: DO NOT USE QUOTES IN CONFIG FILES*

*WARNING: DO NOT USE SPACES IN VARIABLES IN CONFIG FILES, USE "_" INSTEAD*

Fill out this configuration files and go to the next step.
To start the pipeline you should run the following command. 

#+begin_src sh
./02_Run_Pipeline.sh FULL
#+end_src

In the case of *scc4*, the session will be closed after 15 minutes of inactivity. If you want the session to continue, use the *screen* or *tmux* - terminal multiplexers.

If you want to restart the pipeline from any step, just use the following command:

#+begin_src 
./02_Run_Pipeline.sh <short name of step>
# example. ./02_Run_Pipeline.sh 06
#+end_src

* COMMENT Local vars :noexport:
   ;; Local Variables:
   ;; eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)) nil t)
   ;; End:
