#!/bin/bash -l
#$ -cwd
#$ -j y
#$ -e ./logs/
#$ -o ./logs/
#$ -pe omp 8
#$ -l mem_per_core=4G

echo "=========================================================="
Start_Time=$(date +"%s")
echo "Starting on : $(date)"
echo "Running on node   : $(hostname)"
echo "Current job ID    : $JOB_ID"
echo "Current job name  : $JOB_NAME"
echo "Task index number : $TASK_ID"
echo "=========================================================="


function combine_pdfs() {
    local prefix=$1
    local prefix2=$2
    local outname=$3

    pdf_list=($(find . -name "*${prefix}*.pdf" | grep "${prefix2}" | sort))
    echo ${pdf_list}
    pdfunite ${pdf_list[@]} "${outname}"
}

module load R/4.2.3
module load poppler

set +eu
find ../09* -name "*.txt" | grep -E "Up|Down" | grep -vE "DESeq|SEGEX|FullGeneBody" |xargs -n1 -P8 -I{} bash -c "Rscript ./Scripts/clusterProfiler_enrichment.R --input_path {}"

combine_pdfs "top20_bar" "ExonCollapsed" "Combined_ExonCollapsed_top20_bar_output.pdf"
combine_pdfs "top20_dot" "ExonCollapsed" "Combined_ExonCollapsed_top20_dot_output.pdf"
combine_pdfs "top60_bar" "ExonCollapsed" "Combined_ExonCollapsed_top60_bar_output.pdf"
combine_pdfs "top60_dot" "ExonCollapsed" "Combined_ExonCollapsed_top60_dot_output.pdf"
combine_pdfs "MF" "ExonCollapsed" "Combined_ExonCollapsed_MF_ontology_treeveiw.pdf"
combine_pdfs "CC" "ExonCollapsed" "Combined_ExonCollapsed_CC_ontology_treeview.pdf"
combine_pdfs "BP" "ExonCollapsed" "Combined_ExonCollapsed_BP_ontology_treeview.pdf"
combine_pdfs "ALL" "ExonCollapsed" "Combined_ExonCollapsed_ALL_ontologies_treeview.pdf"

set -eu

## remove intermediate clusterProfiler files
find . -name "*.pdf" | grep -v 'Combined' | xargs rm

## move to Job_Summary
mkdir -p Job_Summary/clusterProfiler_ExonCollapsed/xlsx_reports
mv *ExonCollapsed*.pdf ./Job_Summary/clusterProfiler_ExonCollapsed/
mv *ExonCollapsed*.xlsx ./Job_Summary/clusterProfiler_ExonCollapsed/xlsx_reports/

## DAVID downloader and aggregator
echo "Start DAVID downloader"
Rscript ./Scripts/david_downloader.R --input_path "../" # main script dir

echo "Start mx_david_aggregator"
Rscript ./Scripts/mx_david_aggregator.R --input_path ./ \
    --sample_labels ../00_Setup_Pipeline/Sample_Labels.txt \
    --comparisons ../00_Setup_Pipeline/Comparisons.txt

echo "Start alan_david_aggregator"
Rscript ./Scripts/alan_david_aggregator.R --input_path "./" \
    --sample_labels ../00_Setup_Pipeline/Sample_Labels.txt \
    --comparisons ../00_Setup_Pipeline/Comparisons.txt


## move all DAVID aggregated results to summary directory
mkdir -p Job_Summary/DAVID_results/ExonCollapsed/
mkdir -p Job_Summary/DAVID_results/FullGeneBody/
mv *ExonCollapsed*.txt Job_Summary/DAVID_results/ExonCollapsed/
mv *FullGeneBody*.txt Job_Summary/DAVID_results/FullGeneBody/
mv *.xlsx Job_Summary/DAVID_results/

End_Time=$(date +"%s")
diff=$((End_Time - Start_Time))
echo "$((diff / 3600)) hours, $(((diff / 60) % 60)) minutes and $((diff % 60)) seconds elapsed."
echo "=========================================================="
echo "IAMOK"
