#!/bin/bash -l

#$ -cwd
#$ -j y
#$ -o log.txt
#$ -N install_env
#$ -pe omp 1
#$ -l mem_per_core=16G
#$ -l h_rt=06:00:00
#$ -P wax-es


echo "=========================================================="
echo "Starting on       : $(date)"
echo "Running on node   : $(hostname)"
echo "Current job ID    : $JOB_ID"
echo "Current job name  : $JOB_NAME"
echo "Task index number : $TASK_ID"
echo "=========================================================="

module load miniconda

# add channel in oposite order of priority
conda config --add channels defaults
conda config --add channels r
conda config --add channels bioconda
conda config --add channels conda-forge

# make the order strict (1. conda-forge, 2. bioconda, ...)

# create named environment from yml file
conda env create --name RNAseq --file env.yml

echo "Finished  .............. $(date)"
