#!/bin/bash -l
##################################################################################
#Andy Rampersaud, 02.22.16
#This script is called by setup_CollectRnaSeqMetrics.sh
##################################################################################
# Specify which shell to use
#$ -S /bin/bash
# Run on the current working directory
#$ -cwd
#$ -e ./logs/
#$ -o ./logs/
# Join standard output and error to a single file  
#$ -j y
# change to y if you want a single qlog file 
##################################################################################
#Initialize variables from CollectRnaSeqMetrics.sh
##################################################################################

set -o errexit
set -o pipefail
set -o nounset

# export all variables from Pipeline_Setup.conf
eval "$(../00_Setup_Pipeline/01_Pipeline_Setup.py --export)"

#checking the command line arg
#-ne : "is not equal to"
if [ $# -ne 2 ] ; then
      echo "Need 2 arguments for the qsub command: SAMPLE_ID: ${1}, STRAND_SPECIFICITYL ${2}"
      exit 0
fi

# process the command line arguments
SAMPLE_ID=$1
STRAND_SPECIFICITY=$2

# current directory
script_dir="$(pwd)"

#Print variables (make sure they appear correctly):
echo "-----------------------"
echo "Start of variable list:"
echo "-----------------------"
echo "Sample_ID:"
echo ${SAMPLE_ID}
echo "Dataset_DIR:"
echo ${DATASET_DIR}
echo "STRAND_SPECIFICITY:"
echo ${STRAND_SPECIFICITY}
echo "SCRIPT_DIR:"
echo ${script_dir}
echo "-----------------------"
echo "End of variable list"
echo "-----------------------"

start_time=$(date +"%s")

echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
echo "Task index number : $SGE_TASK_ID"
echo "Parameter for multiple cores : $NSLOTS"
echo "=========================================================="

# Go to local scratch directory
echo 'Change dir to scratch directory'
cd "${TMPDIR}"
echo 'Print scratch directory location:'
echo "$TMPDIR"

echo 'Loading required modules...'

#Make sure the shebang line = #!/bin/bash -l
#Need the -l option to load modules
module load picard

# copy user input data files to scratch
cp "${DATASET_DIR}/${SAMPLE_ID}/tophat2/${SAMPLE_ID}_primary_unique.bam" .

#Initialize INPUT_BAM:
input_bam=${SAMPLE_ID}'_primary_unique.bam'

#Copy CollectRnaSeqMetrics required files:
cp "${script_dir}/Input_Regions/genes_refFlat" .
cp "${script_dir}/Input_Regions/rRNA_intervalList_sorted" .

storage_dir=${DATASET_DIR}/${SAMPLE_ID}/tophat2

#Create CollectRnaSeqMetrics output folder to store files:
output_dir='CollectRnaSeqMetrics'
mkdir -p "${output_dir}"

echo 'List files in scratch directory:'
ls -alh
echo 'Starting to run my commands'
echo 'Starting CollectRnaSeqMetrics command'
echo 'Printing command:'
echo

#Run command:
(set -x; picard CollectRnaSeqMetrics REF_FLAT=genes_refFlat RIBOSOMAL_INTERVALS=rRNA_intervalList_sorted STRAND="${STRAND_SPECIFICITY}" INPUT="${input_bam}" OUTPUT="${output_dir}/${SAMPLE_ID}_metrics")

echo 'Finished CollectRnaSeqMetrics command'
echo 'Copy output to storage dir'
cp -r ${output_dir} ${storage_dir}

echo "List files in scratch"
ls -alh

echo "=========================================================="
echo "Finished on : $(date)"
end_time=$(date +"%s")
diff=$((end_time-start_time))
echo "$((diff / 3600)) hours, $(((diff / 60) % 60)) minutes and $((diff % 60)) seconds elapsed."
echo "=========================================================="
echo "IAMOK"
