#!/bin/bash -l

#$ -S /bin/bash
#$ -cwd
#$ -j y
#$ -e ./logs/
#$ -o ./logs/

set -o errexit
set -o pipefail
set -o nounset

module load gcc/8.1.0
module load R/3.6.0

# export all variables from Pipeline_Setup.conf
eval "$(../00_Setup_Pipeline/01_Pipeline_Setup.py --export)"

function calc_correlation()
{
    local SEARCH_BODY=$1
    local OUTDIR=$2

    PCOR=Pearson_correlation
    SCOR=Spearman_correlation
    
    rm -rf PCA && mkdir -p PCA
    rm -rf ${PCOR} && mkdir -p ${PCOR}
    rm -rf ${SCOR} && mkdir -p ${SCOR}

    rm -rf ${OUTDIR} && mkdir -p ${OUTDIR}

    # dd=$(find ../09b_DE_* -name "DiffEx*GeneBody*txt")
    defiles=$(eval find ${SEARCH_BODY})

    for fname in $defiles
    do
	# extract comparison number (09d_1_... --> 1)
	prefix=$(echo $fname | grep -Po "_\K([0-9][0-9]?)(?=_)")
	
	# copy with prefix in the begining
	cp $fname "./${prefix}_$(basename $fname)"
    done
    
    Rscript pearson_script.R $DATASET_LABEL
    
    # mv all plots to corresponding directories
    mv *_Pearson* ./${PCOR}
    mv *_Spearman* ./${SCOR}
    mv *_PCA_* ./PCA/

    # remove all Diff.Exp files
    rm -rf *DiffExp*
    
    # create combined pdf files 
    (cd ${PCOR}; pdfunite $(ls *.pdf | sort -n) ${OUTDIR}_Pearson_Combined.pdf)
    (cd ${SCOR}; pdfunite $(ls *.pdf | sort -n) ${OUTDIR}_Spearman_Combined.pdf)
    (cd PCA; pdfunite $(ls *.pdf | sort -n) ${OUTDIR}_PCA_Combined.pdf)
    mv ${PCOR} ./${OUTDIR}/
    mv ${SCOR} ./${OUTDIR}/
    mv PCA ./${OUTDIR}/
    mv tSNE_All_Merge.pdf ./${OUTDIR}/
}

calc_correlation "../09a_DE_* -name 'DiffEx*GeneBody*txt'" 13a_HTSeq_GeneBody
calc_correlation "../09b_DE_* -name 'DiffEx*GeneBody*txt'" 13b_featureCounts_GeneBody
calc_correlation "../09c_DE_* -name 'DiffEx*ExonCollapsed*txt'" 13c_lncRNA_ExonCollapsed

rm -rf Job_Summary && mkdir -p Job_Summary
mv ./13* ./Job_Summary

## Special symbol that step is ok (do not remove it)
echo "IAMOK"
