#!/bin/bash -l

#$ -S /bin/bash
#$ -cwd
#$ -j y
#$ -e ./logs/
#$ -o ./logs/

set -o errexit
set -o pipefail
set -o nounset

module load gcc/8.1.0
module load R/3.6.0

# export all variables from Pipeline_Setup.conf
eval "$(../00_Setup_Pipeline/01_Pipeline_Setup.py --export)"

function combined_pdf() {
    local OUTNAME=$1
    ALL=$(find . -name "*All*pdf" -o -name "*_Sig*pdf" | sort -n)
    ALL+=" "
    ALL+=$(find . -iname "*_non*.pdf" | sort -n)
    pdfunite $(echo $ALL | paste -s -d " ") ${OUTNAME}
}

function calc_correlation()
{
    local SEARCH_BODY=$1
    local OUTDIR=$2
    local DETITLE=$3

    PCOR=Pearson_correlation
    SCOR=Spearman_correlation
    
    rm -rf PCA && mkdir -p PCA
    rm -rf ${PCOR} && mkdir -p ${PCOR}
    rm -rf ${SCOR} && mkdir -p ${SCOR}

    rm -rf ${OUTDIR} && mkdir -p ${OUTDIR}

    # dd=$(find ../09b_DE_* -name "DiffEx*GeneBody*txt")
    defiles=$(eval find ${SEARCH_BODY})

    for fname in $defiles
    do
	# extract comparison number (09d_1_... --> 1)
	prefix=$(echo $fname | grep -Po "_\K([0-9][0-9]?)(?=_)" | head -n1 |tr -d '\n')
	
	# copy with prefix in the begining
	cp $fname "./${prefix}_$(basename $fname)"
    done
    
    # DATASET_LABEL exported from the Pipeline_Setup.conf, Step_0
    Rscript pearson_script.R $DATASET_LABEL $DETITLE
    
    # mv all plots to corresponding directories
    mv *_Pearson* ./${PCOR}
    mv *_Spearman* ./${SCOR}
    mv *_PCA_* ./PCA/

    # remove all Diff.Exp files
    rm -rf *DiffExp*
    
    # create combined pdf files 
    (cd ${PCOR}; combined_pdf ${OUTDIR}_Pearson_Combined.pdf)
    (cd ${SCOR}; combined_pdf ${OUTDIR}_Spearman_Combined.pdf)
    (cd PCA; combined_pdf ${OUTDIR}_PCA_Combined.pdf)

    mv ${PCOR} ./${OUTDIR}/
    mv ${SCOR} ./${OUTDIR}/
    mv PCA ./${OUTDIR}/
    mv tSNE_All_Merge.pdf ./${OUTDIR}/
}
echo "Start 13a_RefSeq24_HTSeq_ExonCollapsed: $(date)"
calc_correlation "../09a_DE_* -name 'DiffEx*ExonCollapsed*txt'" 13a_RefSeq24_HTSeq_ExonCollapsed RefSeq24k
echo "Start 13b_RefSeq24k_featureCounts_ExonCollapsed: $(date)"
calc_correlation "../09b_DE_* -name 'DiffEx*ExonCollapsed*txt'" 13b_RefSeq24k_featureCounts_ExonCollapsed RefSeq24k
echo "Start 13c_LncRNA15k_ExonCollapsed: $(date)"
calc_correlation "../09c_DE_* -name 'DiffEx*ExonCollapsed*txt'" 13c_LncRNA15k_ExonCollapsed LncRNA15k
echo "Start 13d_RefSeqLncRNA76k_ExonCollapsed: $(date)"
calc_correlation "../09d_DE_* -name 'DiffEx*ExonCollapsed*txt'" 13d_RefSeqLncRNA76k_ExonCollapsed RefSeqLncRNA76k

rm -rf Job_Summary && mkdir -p Job_Summary
mv ./13* ./Job_Summary

## Special symbol that step is ok (do not remove it)
echo "IAMOK"
