#!/bin/bash -l

# compare TACO_REFCOMP_REFERENCE and GTF file to find new isoforms
# OUTPUT:
# tsv file with general information about new isoforms
# gtf (optional) with the same general information

# Specify which shell to use
#$ -S /bin/bash
#$ -cwd
#$ -j y
#$ -e ./logs/
#$ -o ./logs/
#$ -pe omp 8
#$ -l mem_per_core=2G

# set strict options
set -o errexit
set -o pipefail
set -o nounset

# arguments
GROUP=$1
OUTPUT_PREFIX=$2

MAIN_DIR="$(pwd)"

# export all variables from Pipeline_Setup.conf
eval "$(../00_Setup_Pipeline/01_Pipeline_Setup.py --export)"

# activate conda environment
set +eu
module load miniconda
conda activate --stack ${CONDA_DIR}/rlang361
conda activate --stack ${CONDA_DIR}/isoforms
conda activate --stack ${CONDA_DIR}/bedtools
set -eu

start_time=$(date +"%s")

mkdir -p Job_Summary/${OUTPUT_PREFIX}

pushd Job_Summary/${OUTPUT_PREFIX}

if [ "${GROUP}" = "ALL" ]; then
    # all samples with description and color 
    samples=($("${SETUP_PIPELINE_DIR}"/01_Pipeline_Setup.py --samples))
else
    # group samples with condition name and color 
    samples=($("${SETUP_PIPELINE_DIR}"/01_Pipeline_Setup.py --samples_by_group ${GROUP}))
fi

TACO_TMP="${OUTPUT_PREFIX}_TMP"

taco_refcomp -p ${NSLOTS} -o "${TACO_TMP}" -r ${TACO_REFCOMP_REFERENCE}  -t ./${OUTPUT_PREFIX}.gtf

# if TACO GTF combined from groups is required
if [ ${TACO_KEEP_GTF} -eq 0 ]; then
    rm ./${OUTPUT_PREFIX}.gtf
fi

pushd "${TACO_TMP}"

# TSV file postprocessing  
cp ${MAIN_DIR}/Scripts/TSV_processing.R ./
Rscript TSV_processing.R "assembly.metadata" "REFCOMP_${OUTPUT_PREFIX}"
mv "REFCOMP_${OUTPUT_PREFIX}.tsv" ../

# if TACO REFCOMPARE output GTF is required
if [ ${TACO_REFCOMP_KEEP_GTF} -eq 1 ]; then
    mv "assembly.refcomp.gtf" ../"REFCOMP_${OUTPUT_PREFIX}.gtf"     
fi
popd

rm -rf ${TACO_TMP}
popd

# use to calculate job time:
end_time=$(date +"%s")
diff=$((end_time-start_time))
echo "$((diff / 3600)) hours, $(((diff / 60) % 60)) minutes and $((diff % 60)) seconds elapsed."
echo "=========================================================="
echo "IAMOK"
