#!/bin/bash -l

# run assembler (StringTie/)
# INPUT: SAMPLE_ID name
#        OUTPUT dir
# OUTPUT: GTF file inside the OUTPUT dir

# Specify which shell to use
#$ -S /bin/bash
#$ -cwd
#$ -j y
#$ -e ./logs/
#$ -o ./logs/
#$ -pe omp 1

# set strict options
set -o errexit
set -o pipefail
set -o nounset

# arguments
SAMPLE_ID=$1
OUTPUT_DIR=$2

# export all variables from Pipeline_Setup.conf
eval "$(../00_Setup_Pipeline/01_Pipeline_Setup.py --export)"

# activate conda environment
set +eu
module load miniconda
conda activate --stack ${CONDA_DIR}/rlang361
conda activate --stack ${CONDA_DIR}/isoforms
set -eu

# automated strand detection
if [ ${STRANDEDNESS} -eq 3 ]; then
    export_file="${DATASET_DIR}/${SAMPLE_ID}/Read_Strandness/${SAMPLE_ID}_export.sh"
    if [[ -f "${export_file}" ]]; then
	# re-export STRANDEDNESS
	source ${export_file}
	echo "Auto: $STRANDEDNESS"
    else
	echo "Error: cannot find file: ${export_file}"
	echo "To use automatic strand detection, you must complete step 01_Read_Strandness"
	exit 1
    fi
fi

# calculate STRAND_RULE from STRANDEDNESS
if [ ${STRANDEDNESS} -eq 0 ]
then
    STRAND_OPTION=("")
elif [ ${STRANDEDNESS} -eq 2 ]
then
    STRAND_OPTION=("--fr")
elif [ ${STRANDEDNESS} -eq 1 ]
then
    STRAND_OPTION=("--rf")
fi

mkdir -p ${OUTPUT_DIR}

pushd ${OUTPUT_DIR}
stringtie ${STRAND_OPTION[@]} "${DATASET_DIR}/${SAMPLE_ID}/aligner/${SAMPLE_ID}_primary_unique.bam" -o "${SAMPLE_ID}.gtf"
popd

echo "----------"
echo "IAMOK"
